# Generated by Django 6.0.1 on 2026-01-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name_surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='passport_back',
            field=models.ImageField(blank=True, null=True, upload_to='passports/'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='passport_front',
            field=models.ImageField(blank=True, null=True, upload_to='passports/'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='return_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
