# Generated by Django 4.2.16 on 2026-02-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carextra_destination_car_air_conditioning_car_doors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
