# Generated by Django 6.0.1 on 2026-01-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_detail_alter_car_image_alter_car_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='pickup_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='return_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
