# Generated by Django 4.2.16 on 2026-02-13 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_fuel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgCarExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(upload_to='cars/extras/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='cars.car')),
            ],
        ),
    ]
