# Generated by Django 6.0.1 on 2026-02-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='extras',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='carextra',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carextra',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
