# Generated by Django 4.2.16 on 2026-03-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_reservation_car_price_total_reservation_total_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='passport_back',
            new_name='driver_licence_back',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='passport_front',
            new_name='driver_licence_front',
        ),
        migrations.AddField(
            model_name='reservation',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='passports/'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
